---
title: "Dashboard"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyverse)
library(p8105.datasets)
library(plotly)
library(rnoaa)
```

```{r}
data(ny_noaa)
  
  clean_data = 
  sample_n(ny_noaa, 500) %>%
  janitor::clean_names() %>%
  separate(date, into = c("year", "month", "day"), sep = "-") %>%
  mutate(
    tmax = as.numeric(tmax)/10,
    tmin = as.numeric(tmin)/10,
    snow = round(snow*0.03937*4)/4,
    month = recode(month, "01" = "January", "02" = "February", "03" = "March", "04" = "April", "05" = "May", "06" = "June", "07" = "July", "08" = "August", "09" = "September", "10" = "October", "11" = "November", "12" = "December")) %>%
    group_by(id, year, month) %>%
    mutate(
      mean_temp = (tmax + tmin)/2) %>%
    drop_na(mean_temp)
```

Column {data-width=650}
-----------------------------------------------------------------------

### Boxplot: max temperature distribution across months ordered chronologically

```{r box_plot}
clean_data %>% 
  mutate(month = factor(month, levels = month.name)) %>% 
  plot_ly(y = ~tmax, color = ~month, type = "box", colors = "viridis")
```

Column {data-width=350}
-----------------------------------------------------------------------

### Bar graph: mean precipiation observations across months ordered chronologically

```{r bar_graph}
clean_data %>% 
  group_by(month) %>%
  summarize(mean_prcp = mean(prcp, na.rm = TRUE)) %>%
  drop_na(mean_prcp) %>%
  mutate(month = factor(month, levels = month.name)) %>% 
  plot_ly(x = ~month, y = ~mean_prcp, color = ~month, type = "bar", colors = "viridis")
```

### Scatterplot: precipiration level varying by mean temperature

```{r line graph}
clean_data %>% 
  plot_ly(y = ~prcp, x = ~ mean_temp, type = 'scatter', colors = "viridis")
```

 `rmarkdown::render("dashboard.Rmd", output_format = "flexdashboard::flex_dashboard")`